# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointsPlus', '0002_user_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
